Fix outpoint_state index store
RGB-WG/rgb-node pull request #194
Opened 2022-08-12 14:27 UTC by zoedberg

Found a bug calling `outpoint_state`. By calling the method with an empty `Vec<OutPoint>` it correctly returns known allocations, but by calling it with some specific outpoints it returns no allocations.

Investigating this I've found that when storing the index into the DB:
```rust
for seal in genesis.revealed_seals().unwrap_or_default() {
    debug!("Adding outpoint for seal {}", seal);
    let index_id = ChunkId::with_fixed_fragments(seal.txid, seal.vout);
    self.store.insert_into_set(db::OUTPOINTS, index_id, contract_id)?;
}
```
`ChunkId::with_fixed_fragments` receives a `Option<Txid>`.

While, when searching for specific outpoints:

```rust
let indexes = if outpoints.is_empty() {
    self.store.ids(db::OUTPOINTS)?
} else {
    outpoints
        .iter()
        .map(|outpoint| ChunkId::with_fixed_fragments(outpoint.txid, outpoint.vout))
        .collect()
};
```
`ChunkId::with_fixed_fragments` receives a `Txid`.

I've fixed the bug on the store-side by unwrapping the `Option`, since I believe the TXID should always be present at that point, I hope that's correct, otherwise I'll apply the fix on the search-side by wrapping the TXID into an `Option`.

I manually tested it and can confirm that with this fix `outpoint_state` filter works as expected.

2022-08-21 18:55 UTC, dr-orlovsky requested changes
Thank you for catching this!

While your fix is correct, rust stongly discourage use of `unwrap`s in any production code; the `unwrap_or`, `unwrap_or_default` or `expect` should be used instead - or return an error.

I think we should do a `expect("genesis with vout-based seal which passed schema validation")`, to indicate the reason of the crash (genesis must validate absece of vout-based seals at the schema level, and if it is present, the line 167 and 181 above should guarantee that we would never reach this place).

Can you pls update your PR to use `expect`?

2022-08-22 08:45 UTC, zoedberg commented
sure, thanks for the tip. fixed

2022-08-22 15:28 UTC, dr-orlovsky approved these changes
ACK e737bd6c8a723c020305a02565d8649d483d23fb

2022-08-22 15:29 UTC, dr-orlovsky commented
I think this is a breaking change that will invalidate the stash for existing RGB nodes. Will reflect in a release notes of the patch version...

2022-08-22 15:29 UTC, merged