Proposal to unlocking blind utxo
RGB-WG/rgb-node pull request #204
Opened 2022-09-14 16:17 UTC by crisdut

In addition to the changes in #195, I decided to make a change in `consume_transfer` to unlocking _utxo blinding_.

2022-09-15 00:39 UTC, crisdut commented
Hi @zoedberg , I found the bug.

I did not save the new transition in _transitions_ and _transition_txid_ tables. Also, I added the **CloseMethod** property at the `Reveal` object.

Contract state before spend asset:

![image](https://user-images.githubusercontent.com/471380/190282032-72e437d1-e459-418c-9573-1682d8b9113c.png)

Contract state after spend asset:

![image](https://user-images.githubusercontent.com/471380/190282491-bb77336f-8fb5-4cf4-a828-8b231634b0cf.png)

I was able to spend an asset received, and I used the change address twice.

I made the tests with branch bellow (I merged the `fix/process_consignment` branch with `feat/consume-reveal`)
* https://github.com/crisdut/rgb-node/tree/exp/prs

PS: I tested only tapret dbc. I will start tests with opret (I never used this).

2022-09-15 00:39 UTC, crisdut commented
@dr-orlovsky this branch only merged after merge the #195 branch.

Thanks

2022-09-15 00:51 UTC, cryptoquick commented on rpc/src/client.rs
> +            reveal: reveal,
This line can just be `reveal`, not `reveal: reveal`

2022-09-15 01:00 UTC, cryptoquick requested changes
Just some nits, also, can you create steps in the [demo-rgb.sh](https://github.com/LNP-BP/nodes/blob/master/contrib/demo-rgb.sh) to test this as a form of smoke test?

2022-09-15 01:00 UTC, cryptoquick commented on rpc/src/client.rs
> +            reveal: reveal,
This line can just be `reveal`, not `reveal: reveal`

2022-09-15 01:00 UTC, cryptoquick commented on rpc/src/reveal.rs
> +}
I can understand the custom Display impl, but can't you just derive Clone and Debug on the `Reveal` struct?

2022-09-15 01:00 UTC, cryptoquick commented on rpc/src/reveal.rs
> +        println!("{:?}", &s[colon_blind + 1..]);
Should these all be printed, or just debug logs?

2022-09-15 01:00 UTC, cryptoquick commented on src/bucketd/processor.rs
> +                let conseals = consignment
Ah yes, a `conseal`, a concealed seal... :)

2022-09-15 12:36 UTC, zoedberg commented
thanks @crisdut, I confirm you solved the issue I reported and now all rgb-lib tests are passing :)

2022-09-15 14:41 UTC, crisdut commented
> Just some nits, also, can you create steps in the demo-rgb.sh to test this as a form of smoke test?

Thanks for reviewing @cryptoquick!

I will start writing the steps, and I'll let you know when I finish them.

2022-09-15 18:18 UTC, crisdut commented
Hi @cryptoquick,

The instructions: https://github.com/crisdut/nodes/tree/feat/unlocking-blind-utxo

2022-09-15 20:06 UTC, cryptoquick approved these changes
Just reviewed your changes. Looks good!

2022-09-15 20:08 UTC, cryptoquick requested changes
Just realized something, the lints are failing.
Be sure to run: `cargo clippy`

2022-09-18 09:52 UTC, dr-orlovsky commented
I have merged #195, so I assume this needs rebase.

Regarding the question from there, which has caused this PR: why would we need two methods instead of one? Well, there were a clear reason, since I have started with just one method and it didn't worked that way, so I had to made two. I am currently sick and my head is not working properly, so I can't recall what was the problem that caused splitting method in two. It could be that it was related to multisig wallets and interactivity required for managing stash under multisig wallets, such that all parties should do one of these two procedures before any of them would proceed to the second one - or something like that. I will try to re-analyse and recall better once I will recover.

2022-09-18 22:42 UTC, crisdut commented
> I have merged https://github.com/RGB-WG/rgb-node/pull/195, so I assume this needs rebase.

Yes, you are correct.

> Regarding the question from there, which has caused this PR: why would we need two methods instead of one? 

I my not sure about this question, because I followed the recommendations about extended the method `rgb-cli consume` instead create a new method to reveal the confidential transaction.

2022-09-19 10:37 UTC, dr-orlovsky commented
You got me wrong: it was not my question but a quote of Zoe question from here https://github.com/RGB-WG/rgb-node/pull/195#issuecomment-1243346370

And I tried to answer that

2022-09-25 03:29 UTC, crisdut commented
Hi @dr-orlovsky,

I fix the PR.

Can you review this code, please?

2022-09-28 11:13 UTC, dr-orlovsky reviewed
My initial undetstanding was that RGB Node has to keep the blind UTXO secrets it had generated before and use them internally not requiring the client to provide. I do not remember at this moment does the blind UTXO created by the node - or using RGB libs on a wallet side. If the first is correct, than I would have to re-work this PR and complete that workflow. If not, this PR is overall correct - excluding few points I address in the code review comments

2022-09-28 11:13 UTC, dr-orlovsky commented on src/bucketd/processor.rs
> +                    eprintln!(
We must not output to the STDERR - please use `error!` logging instead

2022-09-28 11:13 UTC, dr-orlovsky commented on src/bucketd/processor.rs
> +            }) => {
This is usually done by using `matches!` macro, which avoids the last `_ => none!()` thing. Usually this is reported by the linter - no idea why it passed here, probably linting CI got broken

2022-09-28 16:41 UTC, crisdut commented
> My initial undetstanding was that RGB Node has to keep the blind UTXO secrets it had generated before and use them internally not requiring the client to provide. I do not remember at this moment does the blind UTXO created by the node - or using RGB libs on a wallet side.

Currently, the blind utxo is created with `rgb-std` lib. I think this process is moved to `rgb-std` after version v0.8.0 of the `rgb-node`.

> If not, this PR is overall correct - excluding few points I address in the code review comments

Great! I will try fix it ASAP. Thanks!

2022-09-29 18:23 UTC, cryptoquick approved these changes
Looks like all the linter checks have passed. Clippy is super helpful. LGTM!

2022-09-30 07:38 UTC, dr-orlovsky approved these changes
utACK 2954e697182468a82ef08d3f9d4d62c28d624aa0

2022-09-30 07:39 UTC, merged